### ISSUE TITLE
Issue cloning from Github with SSH

### ISSUE THREAD

**Issue by ursuad** [kubernetes/git-sync#33]
Because of #32 I tried switching to SSH, but the container keeps crashing again. 

The logs are:
```
$ kubectl logs dp-analytics-blog-2fjnv -c git-sync
I0202 13:28:42.608581       1 main.go:162] starting up: ["/git-sync"]
E0202 13:28:43.307843       1 main.go:169] error syncing repo: error running command: exit status 128: "Cloning into '/git'...\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
```

Just to test, I replaced the container command with:
```
#        command: ["cat"]
#        args: ["/etc/git-secret/ssh"]
```
I got the SSH key from the output, removed all my local keys from the SSH agent, imported that key (from the container) with `ssh-add` and it worked to clone the repo.  So it must be something from the container?

My config:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc-name
spec:
  replicas: 1
  template:
    metadata:
      name: my-pod-name
      labels:
        application: my-app
        component: my-comp
        environment: my-env
    spec:
      containers:
      - name: git-sync
        image: gcr.io/google_containers/git-sync:v2.0.4
#        command: ["cat"]
#        args: ["/etc/git-secret/ssh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: "git@github.com:GITHUB_USER/GITHUB_REPO.git"
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEST
          value: git
        - name: GIT_SYNC_DEPTH
          value: "1"
      volumes:
      - name: html
        emptyDir: {}
      - name: git-secret
        secret:
          secretName: github-secret-ssh
          defaultMode: 0400
```

**Comment by stp-ip** [comment]
To "fix" it try running the container with "runAsUser: 0". Still looking into why this works or better why running it without it fails.

Also the recommended container to run is: "gcr.io/google_containers/git-sync-amd64:v2.0.4"

**Comment by stp-ip** [comment]
Just to gather some more info:

What cluster version did you run?
Where did the cluster run? GKE?
Was it an updated version of the cluster?
What was the actual permission on the ssh key?

**Comment by sjernigan** [comment]
See  #34

**Comment by stp-ip** [comment]
Fixed via #37.

**Comment by mgilbir** [comment]
I know this is closed, but I just hit something similar today in a cluster that was working fine until today.
The fix proposed in #37 didn't solve the issue for me.

I ended up changing the deployment to override the default command with `tail -f /dev/null` and I exec'ed into the container to play around.

I was getting the aforementioned error:

```
error syncing repo: error running command: exit status 128: "Cloning into '/git'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```


and running the git clone command directly offered the same output.

Only after getting more debug on the git command I saw the problem:

```
# GIT_SSH_COMMAND="ssh -vvv" git clone git@gitlab.com:myorg/repo.git
Cloning into 'repo'...
OpenSSH_7.2p2-hpn14v4, OpenSSL 1.0.2j  26 Sep 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolving "gitlab.com" port 22
ssh-binary: Could not resolve hostname gitlab.com: Try again
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The container had no DNS because the CNI was borked on that node. After fixing the CNI problems, everything went back to running perfectly without needing to run the container as root.

YMMV but after spending a few hours sorting this out, I thought it might be useful to write it down somewhere for others that have no luck with the runAsRoot fix.

**Comment by fairyhunter13** [comment]
@stp-ip Hello, I still get the same problem with @ursuad in my `GKE cluster`, can you help me?

**Comment by stp-ip** [comment]
@fairyhunter13 What's the specific problem? Which version are you using?

**Comment by fairyhunter13** [comment]
@stp-ip With the latest version. And it seems I always get this log.
```
I1114 15:06:08.050003       1 main.go:269]  "level"=0 "msg"="starting up"  "args"=["/git-sync","-repo=git@github.com:kitabisa/tyk-plugins","-branch=master","-root=/opt/tyk-gateway/plugins","-dest=compiled-plugins","-one-time=true","-ssh=true","-max-sync-failures=3"]
E1114 15:06:08.785486       1 main.go:299]  "msg"="unexpected error syncing repo, will retry" "error"="error running command: exit status 128: \"Cloning into '/opt/tyk-gateway/plugins'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
I1114 15:06:08.785690       1 main.go:300]  "level"=0 "msg"="waiting before retrying"  "waitTime"=0
E1114 15:06:09.514627       1 main.go:299]  "msg"="unexpected error syncing repo, will retry" "error"="error running command: exit status 128: \"Cloning into '/opt/tyk-gateway/plugins'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
I1114 15:06:09.514674       1 main.go:300]  "level"=0 "msg"="waiting before retrying"  "waitTime"=0
E1114 15:06:10.250051       1 main.go:299]  "msg"="unexpected error syncing repo, will retry" "error"="error running command: exit status 128: \"Cloning into '/opt/tyk-gateway/plugins'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
I1114 15:06:10.250094       1 main.go:300]  "level"=0 "msg"="waiting before retrying"  "waitTime"=0
E1114 15:06:11.014989       1 main.go:294]  "msg"="failed to sync repo, aborting" "error"="error running command: exit status 128: \"Cloning into '/opt/tyk-gateway/plugins'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\""
```

**Comment by SingularBunny** [comment]
Could be useful. You could try to use full URL with ssh:// scheme:
ssh://git@yourhost:port/path/repo.git
or with specified port:
ssh://git@yourhost:port/path/repo.git
For me it solved the problem.
